### PR TITLE
Markdown Makerover ✨

### PR DESCRIPTION
**Pull request by Jamesharris10**

### CODE REVIEW

**Review by SaptakBhoumik — CHANGES_REQUESTED** [review]
Requirements.md file is looking good but dont delete the requirements.txt file because without it the process of installing the packages becomes difficult

**Comment by Jamesharris10** [comment]
> Requirements.md file is looking good but dont delete the requirements.txt file because without it the process of installing the packages becomes difficult

Why? As when installing the packages you can just copy and paste the more-beutifal MD?

**Comment by SaptakBhoumik** [comment]
pip3 install -r requirements.txt
This single command can be used instead of copying again and again which makes the work easier

**Comment by Jamesharris10** [comment]
Aha! I see sorry

git close

**Comment by SaptakBhoumik** [comment]
> Aha! I see sorry git close
You can keep the requirements.md

**Comment by Jamesharris10** [comment]
Ok.

Sorrry for wasting your time.

**Comment by SaptakBhoumik** [comment]
@Jamesharris10 create a new pull request with both the requirements.md and requirements.txt

**Pull request closed without merging**
