### PR TITLE
Changed Styling of Home Page, Tabs and URL Bar

### PR DESCRIPTION
**Pull request by LouisKlimek**
I think this new Design is drastically better than the old one, but you be the judge^^
newUI

### CODE REVIEW

**Comment by SaptakBhoumik** [comment]
The latest design is even better so check it out

**Comment by LouisKlimek** [comment]
> 
> 
> The latest design is even better so check it out

image

The latest design looks better than the old one but it is still quite bad. I am currently trying to combine it with my one and then we could have an all round good version^^

**Comment by SaptakBhoumik** [comment]
> The latest design looks better than the old one but it is still quite bad. I am currently trying to combine it with my one and then we could have an all round good version^^

Great idea

**Comment by SaptakBhoumik** [comment]
After changing send me a screenshot

**Comment by LouisKlimek** [comment]
idk why but i currently cant resolve the branch conflict that happend after your minor fix. i closed this Pull request and will open a new one in a sec

**Pull request closed without merging**
